# Generated by Django 5.0.3 on 2024-04-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=25)),
                ('dateAdmited', models.DateTimeField()),
                ('contact', models.CharField(max_length=25)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
