# Generated by Django 5.0.3 on 2024-04-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0005_rename_dateadmited_sitter_date_admitted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='status',
            new_name='duty',
        ),
    ]
